/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentationlayer;

import java.awt.event.ActionListener;


/**
 *
 * @author jnmkimpton
 */
public class CilinderFrame extends javax.swing.JFrame {
    
    private MainFrame mainframe;

    /**
     * new CilinderFrame
     */
    public CilinderFrame(MainFrame mainframe) {
        setLocation(400,400);
        initComponents();
        this.mainframe = mainframe;
    }
    
    /**
     * height
     * 
     * @return height
     */
    public int getHeightValue()
    {
        return Integer.parseInt(txtHeight.getText());
    }
    
    /**
     * radius
     * 
     * @return radius
     */
    public int getRadiusValue()
    {
        return Integer.parseInt(txtRadius.getText());
    }
    
    /**
     * Clear values
     * 
     */
    public void setEmptyValue()
    {
        txtRadius.setText(null);
        txtHeight.setText(null);
    }
    
    /**
     * Cancelbutton actionlistener
     * 
     * @param listenerForCancelButton 
     */
    public void addbtnCancelListener(ActionListener listenerForCancelButton) {
        btnCancel.addActionListener(listenerForCancelButton);
    }
    
    /** 
     * Addbutton actionlistener
     * 
     * @param listenerForAddButton 
     */
    public void addbtnAddShapeListener(ActionListener listenerForAddButton) {
        btnAdd.addActionListener(listenerForAddButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblRadius = new javax.swing.JLabel();
        lblHeigth = new javax.swing.JLabel();
        txtRadius = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cilinder");

        btnAdd.setText("Add");
        btnAdd.setName("Cilinder"); // NOI18N

        btnCancel.setText("Cancel");

        lblRadius.setText("Radius:");

        lblHeigth.setText("Heigth:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRadius)
                                .addGap(18, 18, 18)
                                .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHeigth)
                                .addGap(18, 18, 18)
                                .addComponent(txtHeight)))
                        .addGap(0, 96, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRadius)
                    .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeigth)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel lblHeigth;
    private javax.swing.JLabel lblRadius;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtRadius;
    // End of variables declaration//GEN-END:variables
}
