/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentationlayer;

import java.awt.event.ActionListener;

/**
 *
 * @author jnmkimpton
 */
public class ConeFrame extends javax.swing.JFrame {
    
    private MainFrame mainframe;

    /**
     * new ConeFrame
     */
    public ConeFrame(MainFrame mainframe) {
        setLocation(400,400);
        initComponents();
        this.mainframe = mainframe;
    }
    
    /**
     * Get Height
     * 
     * @return height
     */
    public int getHeightValue()
    {
        return Integer.parseInt(txtHeight.getText());
    }
    
    /**
     * Get Radius
     * 
     * @return the radius
     */
    public int getRadiusValue()
    {
        return Integer.parseInt(txtRadius.getText());
    }
    
    public void setEmptyValue()
    {
        txtHeight.setText(null);
        txtRadius.setText(null);
    }
    
    /**
     * Cancelbutton actionlistener
     * 
     * @param listenerForCancelButton 
     */
    public void addbtnCancelListener(ActionListener listenerForCancelButton) {
        btnCancel.addActionListener(listenerForCancelButton);
    }
    
    /** 
     * Addbutton actionlistener
     * 
     * @param listenerForAddButton 
     */
    public void addbtnAddShapeListener(ActionListener listenerForAddButton) {
        btnAdd.addActionListener(listenerForAddButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeigth = new javax.swing.JLabel();
        lblRadius = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        txtRadius = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeigth.setText("Height");

        lblRadius.setText("Radius");

        btnAdd.setText("Add");
        btnAdd.setName("Cone"); // NOI18N

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblHeigth)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblRadius)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtRadius)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeigth)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRadius)
                    .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel lblHeigth;
    private javax.swing.JLabel lblRadius;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtRadius;
    // End of variables declaration//GEN-END:variables
}
