/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentationlayer;

import java.awt.event.ActionListener;

/**
 *
 * @author jnmkimpton
 */
public class SphereFrame extends javax.swing.JFrame {
    
    private MainFrame mainframe;

    /**
     * new SphereFrame
     */
    public SphereFrame(MainFrame mainframe) {
        setLocation(400,400);
        initComponents();
        this.mainframe = mainframe;
    }
    
    /**
     * radius
     * 
     * @return radius
     */
    public int getRadiusValue()
    {
        return Integer.parseInt(txtRadius.getText());
    }
    
    /**
     * Clear values
     * 
     */
    public void setEmptyValue()
    {
        txtRadius.setText(null);
    }
    
    /**
     * Cancelbutton actionlistener
     * 
     * @param listenerForCancelButton 
     */
    public void addbtnCancelListener(ActionListener listenerForCancelButton) {
        btnCancel.addActionListener(listenerForCancelButton);
    }
    
    /** 
     * Addbutton actionlistener
     * 
     * @param listenerForAddButton 
     */
    public void addbtnAddShapeListener(ActionListener listenerForAddButton) {
        btnAdd.addActionListener(listenerForAddButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRadius = new javax.swing.JLabel();
        txtRadius = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRadius.setText("Radius");

        btnAdd.setText("Add");
        btnAdd.setName("Sphere"); // NOI18N

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRadius)
                        .addGap(18, 18, 18)
                        .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRadius)
                    .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel lblRadius;
    private javax.swing.JTextField txtRadius;
    // End of variables declaration//GEN-END:variables
}

